version: '2'
services:
  quotes:
    image: shahrilx/quotes:${DOCKER_IMAGE_TAG}
    build:
      context: ./QuoteService
      dockerfile: app.dockerfile
  api:
    image: shahrilx/api:${DOCKER_IMAGE_TAG}
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "4000:4000"
  frontend:
    image: shahrilx/frontend:${DOCKER_IMAGE_TAG}
    build:
      context: ./FrontendApplication
      dockerfile: app.dockerfile
    ports:
      - "8000:80"
    
