version: '2'
services:
  quotes:
    image: shahrilx/quotes:@BUILD_NUMBER
    build:
      context: ./QuoteService
      dockerfile: app.dockerfile
  api:
    image: shahrilx/api:@BUILD_NUMBER
    build:
      context: ./ApiGateway
      dockerfile: app.dockerfile
    environment:
      - "QUOTES_API=http://quotes:5000"
    depends_on:
      - quotes
    ports:
      - "4000:4000"
  frontend:
    image: shahrilx/frontend:@BUILD_NUMBER
    build:
      context: ./FrontendApplication
      dockerfile: app.dockerfile
    ports:
      - "8000:80"
    
