global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100
 - job_name: jenkins
   metrics_path: /prometheus
   scheme : http
   static_configs:
    - targets:
       - host.docker.internal:8080
##In grafana to add data source use http://prometheus:9090
